# -*- coding: utf-8 -*-
# list of language codes
# this file is generated automatically by utils/update_search_languages.py

language_codes = (
    (u"ar", u"العربية", u"", u"Arabic"),
    (u"bg", u"Български", u"", u"Bulgarian"),
    (u"ca", u"Català", u"", u"Catalan"),
    (u"cs", u"Čeština", u"", u"Czech"),
    (u"da", u"Dansk", u"", u"Danish"),
    (u"de", u"Deutsch", u"", u"German"),
    (u"el", u"Ελληνικά", u"", u"Greek"),
    (u"en", u"English", u"", u"English"),
    (u"es", u"Español", u"", u"Spanish"),
    (u"et", u"Eesti", u"", u"Estonian"),
    (u"fa", u"فارسی", u"", u"Persian"),
    (u"fi", u"Suomi", u"", u"Finnish"),
    (u"fr", u"Français", u"", u"French"),
    (u"he", u"עברית", u"", u"Hebrew"),
    (u"hr", u"Hrvatski", u"", u"Croatian"),
    (u"hu", u"Magyar", u"", u"Hungarian"),
    (u"id", u"Indonesia", u"", u"Indonesian"),
    (u"is", u"Íslenska", u"", u"Icelandic"),
    (u"it", u"Italiano", u"", u"Italian"),
    (u"ja", u"日本語", u"", u"Japanese"),
    (u"ko", u"한국어", u"", u"Korean"),
    (u"lt", u"Lietuvių", u"", u"Lithuanian"),
    (u"lv", u"Latviešu", u"", u"Latvian"),
    (u"ms", u"Bahasa Melayu", u"", u"Malay"),
    (u"nb", u"Norsk Bokmål", u"", u"Norwegian Bokmål"),
    (u"nl", u"Nederlands", u"", u"Dutch"),
    (u"pl", u"Polski", u"", u"Polish"),
    (u"pt", u"Português", u"", u"Portuguese"),
    (u"ro", u"Română", u"", u"Romanian"),
    (u"ru", u"Русский", u"", u"Russian"),
    (u"sk", u"Slovenčina", u"", u"Slovak"),
    (u"sl", u"Slovenščina", u"", u"Slovenian"),
    (u"sr", u"Српски", u"", u"Serbian"),
    (u"sv", u"Svenska", u"", u"Swedish"),
    (u"th", u"ไทย", u"", u"Thai"),
    (u"tr", u"Türkçe", u"", u"Turkish"),
    (u"uk", u"Українська", u"", u"Ukrainian"),
    (u"vi", u"Tiếng Việt", u"", u"Vietnamese"),
    (u"zh", u"中文", u"", u"Chinese"),
    (u"ja", u"བོད་ཡིག", u"", u"Tibetan
        "),
)
