# -*- coding: utf-8 -*-
# list of language codes
# this file is generated automatically by utils/update_search_languages.py

language_codes = (
    (u"ar-SA", u"العربية", u"", u"Arabic"),
    (u"bg-BG", u"Български", u"", u"Bulgarian"),
    (u"ca-ES", u"Català", u"", u"Catalan"),
    (u"cs-CZ", u"Čeština", u"", u"Czech"),
    (u"da-DK", u"Dansk", u"", u"Danish"),
    (u"de", u"Deutsch", u"", u"German"),
    (u"el-GR", u"Ελληνικά", u"", u"Greek"),
    (u"en", u"English", u"", u"English"),
    (u"es", u"Español", u"", u"Spanish"),
    (u"et-EE", u"Eesti", u"", u"Estonian"),
    (u"fa-IR", u"فارسی", u"", u"Persian"),
    (u"fi-FI", u"Suomi", u"", u"Finnish"),
    (u"fr", u"Français", u"", u"French"),
    (u"he-IL", u"עברית", u"", u"Hebrew"),
    (u"hr-HR", u"Hrvatski", u"", u"Croatian"),
    (u"hu-HU", u"Magyar", u"", u"Hungarian"),
    (u"id-ID", u"Indonesia", u"", u"Indonesian"),
    (u"is-IS", u"Íslenska", u"", u"Icelandic"),
    (u"it-IT", u"Italiano", u"", u"Italian"),
    (u"ja-JP", u"日本語", u"", u"Japanese"),
    (u"ko-KR", u"한국어", u"", u"Korean"),
    (u"lt-LT", u"Lietuvių", u"", u"Lithuanian"),
    (u"lv-LV", u"Latviešu", u"", u"Latvian"),
    (u"ms-MY", u"Bahasa Melayu", u"", u"Malay"),
    (u"nb-NO", u"Norsk Bokmål", u"", u"Norwegian Bokmål"),
    (u"nl", u"Nederlands", u"", u"Dutch"),
    (u"pl-PL", u"Polski", u"", u"Polish"),
    (u"pt", u"Português", u"", u"Portuguese"),
    (u"ro-RO", u"Română", u"", u"Romanian"),
    (u"ru-RU", u"Русский", u"", u"Russian"),
    (u"sk-SK", u"Slovenčina", u"", u"Slovak"),
    (u"sl-SI", u"Slovenščina", u"", u"Slovenian"),
    (u"sr-RS", u"Српски", u"", u"Serbian"),
    (u"sv-SE", u"Svenska", u"", u"Swedish"),
    (u"th-TH", u"ไทย", u"", u"Thai"),
    (u"tr-TR", u"Türkçe", u"", u"Turkish"),
    (u"uk-UA", u"Українська", u"", u"Ukrainian"),
    (u"vi-VN", u"Tiếng Việt", u"", u"Vietnamese"),
    (u"zh", u"中文", u"", u"Chinese"),
)
